# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/iterm_mcp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/iterm_mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/iterm_mcp.proto\x12\titerm_mcp\"\x07\n\x05\x45mpty\"Q\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rpersistent_id\x18\x03 \x01(\t\x12\x15\n\ris_processing\x18\x04 \x01(\x08\"3\n\x0bSessionList\x12$\n\x08sessions\x18\x01 \x03(\x0b\x32\x12.iterm_mcp.Session\"\'\n\x11SessionIdentifier\x12\x12\n\nidentifier\x18\x01 \x01(\t\"2\n\x0eStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"A\n\x13\x43reateLayoutRequest\x12\x13\n\x0blayout_type\x18\x01 \x01(\t\x12\x15\n\rsession_names\x18\x02 \x03(\t\"T\n\x0cWriteRequest\x12\x1a\n\x12session_identifier\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x17\n\x0fwait_for_prompt\x18\x03 \x01(\x08\"B\n\x11ReadOutputRequest\x12\x1a\n\x12session_identifier\x18\x01 \x01(\t\x12\x11\n\tmax_lines\x18\x02 \x01(\x05\" \n\x0eTerminalOutput\x12\x0e\n\x06output\x18\x01 \x01(\t\"F\n\x12\x43ontrolCharRequest\x12\x1a\n\x12session_identifier\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontrol_char\x18\x02 \x01(\t\"W\n\rSessionStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x15\n\rpersistent_id\x18\x03 \x01(\t\x12\x15\n\ris_processing\x18\x04 \x01(\x08\x32\x8f\x04\n\x0cITermService\x12\x38\n\x0cListSessions\x12\x10.iterm_mcp.Empty\x1a\x16.iterm_mcp.SessionList\x12G\n\x0c\x46ocusSession\x12\x1c.iterm_mcp.SessionIdentifier\x1a\x19.iterm_mcp.StatusResponse\x12\x46\n\x0c\x43reateLayout\x12\x1e.iterm_mcp.CreateLayoutRequest\x1a\x16.iterm_mcp.SessionList\x12\x45\n\x0fWriteToTerminal\x12\x17.iterm_mcp.WriteRequest\x1a\x19.iterm_mcp.StatusResponse\x12M\n\x12ReadTerminalOutput\x12\x1c.iterm_mcp.ReadOutputRequest\x1a\x19.iterm_mcp.TerminalOutput\x12P\n\x14SendControlCharacter\x12\x1d.iterm_mcp.ControlCharRequest\x1a\x19.iterm_mcp.StatusResponse\x12L\n\x12\x43heckSessionStatus\x12\x1c.iterm_mcp.SessionIdentifier\x1a\x18.iterm_mcp.SessionStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.iterm_mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=37
  _globals['_EMPTY']._serialized_end=44
  _globals['_SESSION']._serialized_start=46
  _globals['_SESSION']._serialized_end=127
  _globals['_SESSIONLIST']._serialized_start=129
  _globals['_SESSIONLIST']._serialized_end=180
  _globals['_SESSIONIDENTIFIER']._serialized_start=182
  _globals['_SESSIONIDENTIFIER']._serialized_end=221
  _globals['_STATUSRESPONSE']._serialized_start=223
  _globals['_STATUSRESPONSE']._serialized_end=273
  _globals['_CREATELAYOUTREQUEST']._serialized_start=275
  _globals['_CREATELAYOUTREQUEST']._serialized_end=340
  _globals['_WRITEREQUEST']._serialized_start=342
  _globals['_WRITEREQUEST']._serialized_end=426
  _globals['_READOUTPUTREQUEST']._serialized_start=428
  _globals['_READOUTPUTREQUEST']._serialized_end=494
  _globals['_TERMINALOUTPUT']._serialized_start=496
  _globals['_TERMINALOUTPUT']._serialized_end=528
  _globals['_CONTROLCHARREQUEST']._serialized_start=530
  _globals['_CONTROLCHARREQUEST']._serialized_end=600
  _globals['_SESSIONSTATUS']._serialized_start=602
  _globals['_SESSIONSTATUS']._serialized_end=689
  _globals['_ITERMSERVICE']._serialized_start=692
  _globals['_ITERMSERVICE']._serialized_end=1219
# @@protoc_insertion_point(module_scope)
