# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import iterm_mcp_pb2 as protos_dot_iterm__mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/iterm_mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ITermServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/iterm_mcp.ITermService/ListSessions',
                request_serializer=protos_dot_iterm__mcp__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.SessionList.FromString,
                _registered_method=True)
        self.FocusSession = channel.unary_unary(
                '/iterm_mcp.ITermService/FocusSession',
                request_serializer=protos_dot_iterm__mcp__pb2.SessionIdentifier.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateLayout = channel.unary_unary(
                '/iterm_mcp.ITermService/CreateLayout',
                request_serializer=protos_dot_iterm__mcp__pb2.CreateLayoutRequest.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.SessionList.FromString,
                _registered_method=True)
        self.WriteToTerminal = channel.unary_unary(
                '/iterm_mcp.ITermService/WriteToTerminal',
                request_serializer=protos_dot_iterm__mcp__pb2.WriteRequest.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ReadTerminalOutput = channel.unary_unary(
                '/iterm_mcp.ITermService/ReadTerminalOutput',
                request_serializer=protos_dot_iterm__mcp__pb2.ReadOutputRequest.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.TerminalOutput.FromString,
                _registered_method=True)
        self.SendControlCharacter = channel.unary_unary(
                '/iterm_mcp.ITermService/SendControlCharacter',
                request_serializer=protos_dot_iterm__mcp__pb2.ControlCharRequest.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CheckSessionStatus = channel.unary_unary(
                '/iterm_mcp.ITermService/CheckSessionStatus',
                request_serializer=protos_dot_iterm__mcp__pb2.SessionIdentifier.SerializeToString,
                response_deserializer=protos_dot_iterm__mcp__pb2.SessionStatus.FromString,
                _registered_method=True)


class ITermServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FocusSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLayout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteToTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTerminalOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControlCharacter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ITermServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=protos_dot_iterm__mcp__pb2.Empty.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.SessionList.SerializeToString,
            ),
            'FocusSession': grpc.unary_unary_rpc_method_handler(
                    servicer.FocusSession,
                    request_deserializer=protos_dot_iterm__mcp__pb2.SessionIdentifier.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'CreateLayout': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLayout,
                    request_deserializer=protos_dot_iterm__mcp__pb2.CreateLayoutRequest.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.SessionList.SerializeToString,
            ),
            'WriteToTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteToTerminal,
                    request_deserializer=protos_dot_iterm__mcp__pb2.WriteRequest.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'ReadTerminalOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTerminalOutput,
                    request_deserializer=protos_dot_iterm__mcp__pb2.ReadOutputRequest.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.TerminalOutput.SerializeToString,
            ),
            'SendControlCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControlCharacter,
                    request_deserializer=protos_dot_iterm__mcp__pb2.ControlCharRequest.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'CheckSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSessionStatus,
                    request_deserializer=protos_dot_iterm__mcp__pb2.SessionIdentifier.FromString,
                    response_serializer=protos_dot_iterm__mcp__pb2.SessionStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iterm_mcp.ITermService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iterm_mcp.ITermService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ITermService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/ListSessions',
            protos_dot_iterm__mcp__pb2.Empty.SerializeToString,
            protos_dot_iterm__mcp__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FocusSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/FocusSession',
            protos_dot_iterm__mcp__pb2.SessionIdentifier.SerializeToString,
            protos_dot_iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/CreateLayout',
            protos_dot_iterm__mcp__pb2.CreateLayoutRequest.SerializeToString,
            protos_dot_iterm__mcp__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteToTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/WriteToTerminal',
            protos_dot_iterm__mcp__pb2.WriteRequest.SerializeToString,
            protos_dot_iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTerminalOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/ReadTerminalOutput',
            protos_dot_iterm__mcp__pb2.ReadOutputRequest.SerializeToString,
            protos_dot_iterm__mcp__pb2.TerminalOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControlCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/SendControlCharacter',
            protos_dot_iterm__mcp__pb2.ControlCharRequest.SerializeToString,
            protos_dot_iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/CheckSessionStatus',
            protos_dot_iterm__mcp__pb2.SessionIdentifier.SerializeToString,
            protos_dot_iterm__mcp__pb2.SessionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
