# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import iterm_mcp_pb2 as iterm__mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in iterm_mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ITermServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/iterm_mcp.ITermService/ListSessions',
                request_serializer=iterm__mcp__pb2.Empty.SerializeToString,
                response_deserializer=iterm__mcp__pb2.SessionList.FromString,
                _registered_method=True)
        self.FocusSession = channel.unary_unary(
                '/iterm_mcp.ITermService/FocusSession',
                request_serializer=iterm__mcp__pb2.SessionIdentifier.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CheckSessionStatus = channel.unary_unary(
                '/iterm_mcp.ITermService/CheckSessionStatus',
                request_serializer=iterm__mcp__pb2.SessionIdentifier.SerializeToString,
                response_deserializer=iterm__mcp__pb2.SessionStatus.FromString,
                _registered_method=True)
        self.SetActiveSession = channel.unary_unary(
                '/iterm_mcp.ITermService/SetActiveSession',
                request_serializer=iterm__mcp__pb2.SetActiveSessionRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateSessions = channel.unary_unary(
                '/iterm_mcp.ITermService/CreateSessions',
                request_serializer=iterm__mcp__pb2.CreateSessionsRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.CreateSessionsResponse.FromString,
                _registered_method=True)
        self.WriteToSessions = channel.unary_unary(
                '/iterm_mcp.ITermService/WriteToSessions',
                request_serializer=iterm__mcp__pb2.WriteToSessionsRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.WriteToSessionsResponse.FromString,
                _registered_method=True)
        self.ReadSessions = channel.unary_unary(
                '/iterm_mcp.ITermService/ReadSessions',
                request_serializer=iterm__mcp__pb2.ReadSessionsRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.ReadSessionsResponse.FromString,
                _registered_method=True)
        self.SendControlCharacter = channel.unary_unary(
                '/iterm_mcp.ITermService/SendControlCharacter',
                request_serializer=iterm__mcp__pb2.ControlCharRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/iterm_mcp.ITermService/RegisterAgent',
                request_serializer=iterm__mcp__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.Agent.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/iterm_mcp.ITermService/ListAgents',
                request_serializer=iterm__mcp__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.AgentList.FromString,
                _registered_method=True)
        self.RemoveAgent = channel.unary_unary(
                '/iterm_mcp.ITermService/RemoveAgent',
                request_serializer=iterm__mcp__pb2.AgentIdentifier.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CreateTeam = channel.unary_unary(
                '/iterm_mcp.ITermService/CreateTeam',
                request_serializer=iterm__mcp__pb2.CreateTeamRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.Team.FromString,
                _registered_method=True)
        self.ListTeams = channel.unary_unary(
                '/iterm_mcp.ITermService/ListTeams',
                request_serializer=iterm__mcp__pb2.Empty.SerializeToString,
                response_deserializer=iterm__mcp__pb2.TeamList.FromString,
                _registered_method=True)
        self.RemoveTeam = channel.unary_unary(
                '/iterm_mcp.ITermService/RemoveTeam',
                request_serializer=iterm__mcp__pb2.TeamIdentifier.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AssignAgentToTeam = channel.unary_unary(
                '/iterm_mcp.ITermService/AssignAgentToTeam',
                request_serializer=iterm__mcp__pb2.AgentTeamAssignment.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RemoveAgentFromTeam = channel.unary_unary(
                '/iterm_mcp.ITermService/RemoveAgentFromTeam',
                request_serializer=iterm__mcp__pb2.AgentTeamAssignment.SerializeToString,
                response_deserializer=iterm__mcp__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SendCascadeMessage = channel.unary_unary(
                '/iterm_mcp.ITermService/SendCascadeMessage',
                request_serializer=iterm__mcp__pb2.CascadeMessageRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.CascadeMessageResponse.FromString,
                _registered_method=True)
        self.OrchestratePlaybook = channel.unary_unary(
                '/iterm_mcp.ITermService/OrchestratePlaybook',
                request_serializer=iterm__mcp__pb2.OrchestrateRequest.SerializeToString,
                response_deserializer=iterm__mcp__pb2.OrchestrateResponse.FromString,
                _registered_method=True)


class ITermServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSessions(self, request, context):
        """Session operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FocusSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetActiveSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSessions(self, request, context):
        """Create sessions with layout
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteToSessions(self, request, context):
        """Write/Read with array-based parallel support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControlCharacter(self, request, context):
        """Control characters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Agent management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTeam(self, request, context):
        """Team management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignAgentToTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAgentFromTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCascadeMessage(self, request, context):
        """Cascading messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrchestratePlaybook(self, request, context):
        """High-level orchestration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ITermServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=iterm__mcp__pb2.Empty.FromString,
                    response_serializer=iterm__mcp__pb2.SessionList.SerializeToString,
            ),
            'FocusSession': grpc.unary_unary_rpc_method_handler(
                    servicer.FocusSession,
                    request_deserializer=iterm__mcp__pb2.SessionIdentifier.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'CheckSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSessionStatus,
                    request_deserializer=iterm__mcp__pb2.SessionIdentifier.FromString,
                    response_serializer=iterm__mcp__pb2.SessionStatus.SerializeToString,
            ),
            'SetActiveSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SetActiveSession,
                    request_deserializer=iterm__mcp__pb2.SetActiveSessionRequest.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'CreateSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSessions,
                    request_deserializer=iterm__mcp__pb2.CreateSessionsRequest.FromString,
                    response_serializer=iterm__mcp__pb2.CreateSessionsResponse.SerializeToString,
            ),
            'WriteToSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteToSessions,
                    request_deserializer=iterm__mcp__pb2.WriteToSessionsRequest.FromString,
                    response_serializer=iterm__mcp__pb2.WriteToSessionsResponse.SerializeToString,
            ),
            'ReadSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSessions,
                    request_deserializer=iterm__mcp__pb2.ReadSessionsRequest.FromString,
                    response_serializer=iterm__mcp__pb2.ReadSessionsResponse.SerializeToString,
            ),
            'SendControlCharacter': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControlCharacter,
                    request_deserializer=iterm__mcp__pb2.ControlCharRequest.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=iterm__mcp__pb2.RegisterAgentRequest.FromString,
                    response_serializer=iterm__mcp__pb2.Agent.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=iterm__mcp__pb2.ListAgentsRequest.FromString,
                    response_serializer=iterm__mcp__pb2.AgentList.SerializeToString,
            ),
            'RemoveAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAgent,
                    request_deserializer=iterm__mcp__pb2.AgentIdentifier.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'CreateTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTeam,
                    request_deserializer=iterm__mcp__pb2.CreateTeamRequest.FromString,
                    response_serializer=iterm__mcp__pb2.Team.SerializeToString,
            ),
            'ListTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=iterm__mcp__pb2.Empty.FromString,
                    response_serializer=iterm__mcp__pb2.TeamList.SerializeToString,
            ),
            'RemoveTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTeam,
                    request_deserializer=iterm__mcp__pb2.TeamIdentifier.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'AssignAgentToTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignAgentToTeam,
                    request_deserializer=iterm__mcp__pb2.AgentTeamAssignment.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'RemoveAgentFromTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAgentFromTeam,
                    request_deserializer=iterm__mcp__pb2.AgentTeamAssignment.FromString,
                    response_serializer=iterm__mcp__pb2.StatusResponse.SerializeToString,
            ),
            'SendCascadeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCascadeMessage,
                    request_deserializer=iterm__mcp__pb2.CascadeMessageRequest.FromString,
                    response_serializer=iterm__mcp__pb2.CascadeMessageResponse.SerializeToString,
            ),
            'OrchestratePlaybook': grpc.unary_unary_rpc_method_handler(
                    servicer.OrchestratePlaybook,
                    request_deserializer=iterm__mcp__pb2.OrchestrateRequest.FromString,
                    response_serializer=iterm__mcp__pb2.OrchestrateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iterm_mcp.ITermService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iterm_mcp.ITermService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ITermService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/ListSessions',
            iterm__mcp__pb2.Empty.SerializeToString,
            iterm__mcp__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FocusSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/FocusSession',
            iterm__mcp__pb2.SessionIdentifier.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/CheckSessionStatus',
            iterm__mcp__pb2.SessionIdentifier.SerializeToString,
            iterm__mcp__pb2.SessionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetActiveSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/SetActiveSession',
            iterm__mcp__pb2.SetActiveSessionRequest.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/CreateSessions',
            iterm__mcp__pb2.CreateSessionsRequest.SerializeToString,
            iterm__mcp__pb2.CreateSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteToSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/WriteToSessions',
            iterm__mcp__pb2.WriteToSessionsRequest.SerializeToString,
            iterm__mcp__pb2.WriteToSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/ReadSessions',
            iterm__mcp__pb2.ReadSessionsRequest.SerializeToString,
            iterm__mcp__pb2.ReadSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControlCharacter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/SendControlCharacter',
            iterm__mcp__pb2.ControlCharRequest.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/RegisterAgent',
            iterm__mcp__pb2.RegisterAgentRequest.SerializeToString,
            iterm__mcp__pb2.Agent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/ListAgents',
            iterm__mcp__pb2.ListAgentsRequest.SerializeToString,
            iterm__mcp__pb2.AgentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/RemoveAgent',
            iterm__mcp__pb2.AgentIdentifier.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/CreateTeam',
            iterm__mcp__pb2.CreateTeamRequest.SerializeToString,
            iterm__mcp__pb2.Team.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/ListTeams',
            iterm__mcp__pb2.Empty.SerializeToString,
            iterm__mcp__pb2.TeamList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/RemoveTeam',
            iterm__mcp__pb2.TeamIdentifier.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignAgentToTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/AssignAgentToTeam',
            iterm__mcp__pb2.AgentTeamAssignment.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAgentFromTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/RemoveAgentFromTeam',
            iterm__mcp__pb2.AgentTeamAssignment.SerializeToString,
            iterm__mcp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCascadeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/SendCascadeMessage',
            iterm__mcp__pb2.CascadeMessageRequest.SerializeToString,
            iterm__mcp__pb2.CascadeMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrchestratePlaybook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iterm_mcp.ITermService/OrchestratePlaybook',
            iterm__mcp__pb2.OrchestrateRequest.SerializeToString,
            iterm__mcp__pb2.OrchestrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
